#ifndef __CFG_AUTO__
#define __CFG_AUTO__

#define CONFIG_NUM 30

#define CFG_MAIN_FONT 0
#define CFG_MAIN_FONT_HEIGHT_REDUCTION 1
#define CFG_POSBOX_FONT 2
#define CFG_FOCUS_FOLLOWS_MOUSE 3
#define CFG_AUTOINDENT 4
#define CFG_SPACEMAN 5
#define CFG_WARP_MOUSE 6
#define CFG_INTERACTIVE_SEARCH_CASE_SENSITIVE 7
#define CFG_AUTOWRAP 8
#define CFG_TAB_WIDTH 9
#define CFG_EDITOR_BG_COLOR 10
#define CFG_EDITOR_FG_COLOR 11
#define CFG_EDITOR_SEL_COLOR 12
#define CFG_EDITOR_BG_CURSORLINE 13
#define CFG_POSBOX_BORDER_COLOR 14
#define CFG_POSBOX_BG_COLOR 15
#define CFG_POSBOX_FG_COLOR 16
#define CFG_BORDER_COLOR 17
#define CFG_TAG_BG_COLOR 18
#define CFG_TAG_FG_COLOR 19
#define CFG_TAG_FONT 20
#define CFG_LEXY_NOTHING 21
#define CFG_LEXY_KEYWORD 22
#define CFG_LEXY_ID 23
#define CFG_LEXY_COMMENT 24
#define CFG_LEXY_STRING 25
#define CFG_LEXY_LITERAL 26
#define CFG_LEXY_FILE 27
#define CFG_TAGS_DISCARD_LINENO 28
#define CFG_AUTORELOAD 29

#endif
