#!/bin/bash

if [ $# -eq 1 ]; then
	find ./ -name '*.c' -or -name '*.cc' -or -name '*.cpp' -or -name '*.h' -or -name '*.py' -or -name '*.txt' -or -name '*.pl' -or -name '*.tcl' -or -name '*.java' -or -name '*.js' -or -name '*.html' -or -name '*.go' -or -name '*.clj' | xargs grep -n $1
else
	grep -Rn --exclude=tags $*
fi


